### ISSUE TITLE
Unreliable operation with Amazon Cloud HSM

### ISSUE THREAD

**Issue by samiponkanen** [miekg/pkcs11#112]
Not sure if this is a problem with miekg/pkcs11 or Amazon Cloud HSM, but I am facing sever reliability problems.

Most of the time all pkcs#11 calls seem to work just fine, but sometimes I get random errors like CKR_DEVICE_MEMORY, CKR_GENERAL_ERROR or CKR_OBJECT_HANDLE_INVALID. I am seeing these errors when running a go test program both single threaded and multi threaded. Obviously running multi threaded I see the errors more often.

I was able to produce CKR_DEVICE_MEMORY and CKR_OBJECT_HANDLE_INVALID errors also by running (a fixed version of) miekg/pkcs11/parallel_test.go in a while loop:
```
--- FAIL: TestParallel (0.14s)
    parallel_test.go:215: Problem making signer: pkcs11: 0x31: CKR_DEVICE_MEMORY
FAIL
```
```
2019/04/18 11:05:44 SignInit: pkcs11: 0x82: CKR_OBJECT_HANDLE_INVALID
```
The CKR_DEVICE_MEMORY seems to occur when setting up the sessions and could therefore be a side effect of running the test again immediately after the previous run ended. The CKR_OBJECT_HANDLE_INVALID error seems more worrying though.

Anyone else facing problems with miekg/pkcs11 + Amazon Cloud HSM?

parallel_test.go.diff:
```diff --git a/parallel_test.go b/parallel_test.go
index aee49bc..f7102f7 100644
--- a/parallel_test.go
+++ b/parallel_test.go
@@ -121,8 +121,11 @@ func makeSigner(context *Ctx) (*signer, error) {
        }
 
        if err = context.Login(session, CKU_USER, pin); err != nil {
-               context.CloseSession(session)
-               return nil, err
+               // Ignore CKR_USER_ALREADY_LOGGED_IN errors
+               if rv, ok := err.(Error); !ok || rv != CKR_USER_ALREADY_LOGGED_IN {
+                       context.CloseSession(session)
+                       return nil, err
+               }
        }
 
        privateKey, err := getPrivateKey(context, session, privateKeyLabel)
@@ -187,7 +190,7 @@ func (c *cache) sign(input []byte) ([]byte, error) {
 }
 
 // TODO(miek): disabled for now. Fill out the correct values in hsm.db so we can use it.
-func testParallel(t *testing.T) {
+func TestParallel(t *testing.T) {
        if module == "" || tokenLabel == "" || pin == "" || privateKeyLabel == "" {
                t.Fatal("Must pass all flags: module, tokenLabel, pin, and privateKeyLabel")
                return
```

**Comment by samiponkanen** [comment]
Update:
While the CKR_OBJECT_HANDLE_INVALID I got earlier might have been a user error, I also got a CKR_KEY_FUNCTION_NOT_PERMITTED after running parallel_test.go:

C_SignInit failed with error CKR_KEY_FUNCTION_NOT_PERMITTED : 0x00000068
2019/04/19 10:14:48 SignInit: pkcs11: 0x68: CKR_KEY_FUNCTION_NOT_PERMITTED

**Comment by camilog** [comment]
I'm facing a similar error using softhsm. Every minute I need to perform a signature. Most of time it works perfectly fine, but sometimes it throws a CKR_KEY_FUNCTION_NOT_PERMITTED error.
