### ISSUE TITLE
Constants can cause int overflow errors on 32-bit platforms

### ISSUE THREAD

**Issue by JeremyRand** [miekg/pkcs11#117]
Doing stuff like this:

~~~
x := *pkcs11.NewAttribute(pkcs11.CKA_TRUST_SERVER_AUTH, pkcs11.CKT_NSS_NOT_TRUSTED)
~~~

Causes an error like this on 32-bit platforms:

~~~
constant 3461563226 overflows int
~~~

Tested on both 32-bit x86 and 32-bit ARM.  I think it's because a lot of the constants in `const.go` and `vendor.go` aren't explicitly declared as `uint`, so Go treats them as `int`, which is only large enough to hold unsigned 32-bit integers when compiled for a 64-bit platform.  Explicitly declaring those constants as `uint` would probably fix it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/pkcs11] Constants can cause ..." ]
>Doing stuff like this:
>
>~~~
>x := *pkcs11.NewAttribute(attr.Type, pkcs11.CKT_NSS_NOT_TRUSTED)
>~~~
>
>Causes an error like this on 32-bit platforms:
>
>~~~
>constant 3461563226 overflows int
>~~~

CKM_VENDOR_DEFINED                   = 0x80000000

is what we have. Constant are typeless in Go.

If this value is too big you probably need to convert it to it int64 your self.

/Miek

--
Miek Gieben

**Comment by JeremyRand** [comment]
Yeah, I think you're right, my bad.  Closing.
