### ISSUE TITLE
Runtime error inside golang:1.12.7-alpine3.9 docker

### ISSUE THREAD

**Issue by vieiramanoel** [miekg/pkcs11#120]
Trying to run sample code inside golang container
I've added
git, gcc and libc-dev to image by running 

`apk add --no-cache git gcc libc-dev`

after that I tried to run 

`go run pkcs11.go` 

inside container and output is

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49b1a2]

goroutine 1 [running]:
github.com/miekg/pkcs11.(*Ctx).Initialize.func1(0x0, 0xc0000a2020)
        /go/pkg/mod/github.com/miekg/pkcs11@v1.0.2/pkcs11.go:805 +0x22
github.com/miekg/pkcs11.(*Ctx).Initialize(0x0, 0x12, 0x0)
        /go/pkg/mod/github.com/miekg/pkcs11@v1.0.2/pkcs11.go:805 +0x2b
main.main()
        /hsm-test/pcks11.go:19 +0x164
exit status 2
```

when I run in host machine everything works and string digest is calculated successfully

**Comment by miekg** [comment]
dont use alpine

**Comment by vieiramanoel** [comment]
Well, fabric-ca image from Hyperledger Fabric project is built on alpine, would be very bad not working on alpine

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/pkcs11] Runtime error in..." ]
>Well, fabric-ca image from Hyperledger Fabric project is built on alpine, would be very bad not working on alpine

happy to merge any (small) changes you find to make this work. I don't have any 
alpine systems laying around so I can't help you

**Comment by vieiramanoel** [comment]
@miekg I've changed docker image to docker's ubuntu oficial one, installed all necessary packages as well as golang and still: same error. At host machine everything works, but I need to deploy it inside a container, can you help me on this?


```
FROM ubuntu:18.04

RUN apt update
RUN apt install -y apt-utils
RUN apt install -y wget git gcc lidbc-dev
RUN wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.12.7.linux-amd64.tar.gz
RUN export PATH=$PATH:/usr/local/go/bin
RUN echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bashrc
```
> Dockerfile for image creation

**Comment by prabhjyot01** [comment]
My project was based on alpine. I'm running into the same issue. Is there any recommended base image to have it perfectly work? Image size is a major concern for me

It works with ubuntu base image but that makes my image size go from 35mb using alpine to around 160mb in ubuntu
