### ISSUE TITLE
Support for pkcs11 URIs

### ISSUE THREAD

**Issue by stefanberger** [miekg/pkcs11#129]
Hello!

 I have created a small library for pkcs11 URI parsing and formatting following [RFC 7512](https://tools.ietf.org/html/rfc7512). The purpose is to use pkcs11 URIs to feed parameters into you pkcs11 client. Would you be interested in adding such code to this project for everyone else to be able to use it? 

The location of the code is currently [here](https://github.com/stefanberger/go-pkcs11uri).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/pkcs11] Support for pkcs11 U..." ]
>Hello!
>
>I have created a small library for pkcs11 URI parsing and formatting following
>RFC 7512. The purpose is to use pkcs11 URIs to feed parameters into you pkcs11
>client. Would you be interested in adding such code to this project for
>everyone else to be able to use it?
>
>The location of the code is currently here.

Thanks, that looks nice. TIL about RFC 7512. However your code is distinct from what this
lib is: providing a Go wrapper for pkcs11, so I don't think it should me merged into this
repo.

happy to point to your repo frmo the README if you send a PR.

Cheers!

**Comment by stefanberger** [comment]
@miekg Your example just got a bit more verbose: https://github.com/stefanberger/go-pkcs11uri#example
