### ISSUE TITLE
Support for CKM_EDDSA

### ISSUE THREAD

**Issue by camilog** [miekg/pkcs11#134]
Hello!
The EdDSA mechanism was introduced in version 3.0 of PKCS#11
https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/os/pkcs11-curr-v3.0-os.html#_Toc30061191

Is it possible to incorporate it in this library?
Regards!

**Comment by zosocanuck** [comment]
PR #145 in flight.

**Comment by miekg** [comment]
has been removed in #147, see #146 for upgrading to v3
