### ISSUE TITLE
Two constants no longer exit

### ISSUE THREAD

**Issue by johann-pfefferl** [miekg/pkcs11#149]
When I upgrade my project to the newest release I get the following error

```
github.com/ThalesIgnite/crypto11
# github.com/ThalesIgnite/crypto11
../../../pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:356:25: undefined: pkcs11.CK_EFFECTIVELY_INFINITE
../../../pkg/mod/github.com/!thales!ignite/crypto11@v1.2.5/crypto11.go:356:79: undefined: pkcs11.CK_UNAVAILABLE_INFORMATION
```

I don't know if this is a problem of the crypto11 package or the pkcs11.

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/pkcs11] Two constants no lon..." ]
>When I upgrade my project to the newest release I get the following error
>
>github.com/ThalesIgnite/crypto11
># github.com/ThalesIgnite/crypto11
***@***.***/crypto11.go:356:25: undefined: pkcs11.CK_EFFECTIVELY_INFINITE
***@***.***/crypto11.go:356:79: undefined: pkcs11.CK_UNAVAILABLE_INFORMATION
>
>I don't know if this is a problem of the crypto11 package or the pkcs11.

I've reparsed everything from pkcs11t.h in #147, either I made a mistake there or these
constants don't exit in the spec

**Comment by miekg** [comment]
[ Quoting ***@***.***> in "[miekg/pkcs11] Two constants no lon..." ]
>When I upgrade my project to the newest release I get the following error
>
>github.com/ThalesIgnite/crypto11
># github.com/ThalesIgnite/crypto11
***@***.***/crypto11.go:356:25: undefined: pkcs11.CK_EFFECTIVELY_INFINITE
***@***.***/crypto11.go:356:79: undefined: pkcs11.CK_UNAVAILABLE_INFORMATION
>
>I don't know if this is a problem of the crypto11 package or the pkcs11.

yep I know, i filter CK_ prefixes, because a lot of them looks off, apparently not. Should
be a quick fix.
