### ISSUE TITLE
Issues with Go 1.6 cgo pointer rules

### ISSUE THREAD

**Issue by zenazn** [miekg/pkcs11#15]
Go 1.6 is [changing its rules][cgo] around passing Go-owned pointers to C. In particular, you may no longer pass Go pointers which contain Go pointers to C. This obviously poses a serious problem for e.g., `cMechanismList` and `cAttributeList` and other internal abstractions, where ~all the memory in a deeply-nested data structure is owned by Go.

Are there any plans to fix this package to comply with Go 1.6's pointer ownership rules?

[cgo]: https://github.com/golang/proposal/blob/master/design/12416-cgo-pointers.md

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[pkcs11] Issues with Go 1.6 cgo poi..." ]
>Go 1.6 is [changing its rules][cgo] around passing Go-owned pointers to C. In particular, you may no longer pass Go pointers which contain Go pointers to C. This obviously poses a serious problem for e.g., `cMechanismList` and `cAttributeList` and other internal abstractions, where ~all the memory in a deeply-nested data structure is owned by Go.
>
>Are there any plans to fix this package to comply with Go 1.6's pointer ownership rules?

Uhm, no... because this is the first time I hear about it. How final is this? 

/Miek

--
Miek Gieben

**Comment by zenazn** [comment]
It's already committed in tip, and I think 1.6 is already frozen.

**Comment by miekg** [comment]
Isn't this covered by the go 1 guarantee then?

And if this will happen, then of course PRs welcome :)

**Comment by FiloSottile** [comment]
It was very much undefined before (and it would blow up pretty easily). This proposal while changing it also commits it, making it included in the Go 1 guarantee (but not retroactively).

> This rules are intended to extend the Go 1 compatibility guidelines to the cgo interface.

**Comment by miekg** [comment]
Ack. I won't push back on this change. Also didn't check what actually needs to be changed in pkcs11 here to make it work with 1.6

**Comment by miekg** [comment]
@zenazn does this PR fix all the pointer issues from 1.6 or are there still issues left after this has been merged?

**Comment by zenazn** [comment]
Not sure, but it fixes all the parts of the API my code exercised, and a light skim of the remainder of the code doesn't show anything obvious. Unfortunately the pointer check is a runtime check, so it's hard to know for sure without trying everything.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [pkcs11] Issues with Go 1.6 cgo..." ]
>Not sure, but it fixes all the parts of the API my code exercised, and a light skim of the remainder of the code doesn't show anything obvious. Unfortunately the pointer check is a runtime check, so it's hard to know for sure without trying everything.

Ack. I *might* have some time tomorrow to get some better tests in.

/Miek

--
Miek Gieben
