### ISSUE TITLE
RFE: Load p11-kit-proxy.so as default provider

### ISSUE THREAD

**Issue by dwmw2** [miekg/pkcs11#171]
Many systems (including most Linux distributions) have a system-wide configuration for PKCS#11 providers, managed by p11-kit. A properly packaged provider will ship with a p11-kit .module file which makes it 'discoverable'.

Users should expect that they can just say something like `pkcs11:manufacturer=piv_II;id=%01` in place of a filename for a certificate/key, and it should Just Work.

Applications using PKCS#11 shouldn't need the user to specify the provider library except in exceptional circumstances (in which case, the `module-path` of the PKCS#11 URI can be used). Where `p11-kit-proxy.so` (or `p11-kit-proxy.dylib`) exists, please use it by default if no other provider is specified.

**Comment by miekg** [comment]
what library are we building here, then?

**Comment by dwmw2** [comment]
> what library are we building here, then?

My vision? A library which makes it easy for application authors to "[Do The Right Thing](https://www.ietf.org/archive/id/draft-woodhouse-cert-best-practice-00.html)" and have a nice simple user interface that just works consistently.

In the case of PKCS#11, applications should just accept PKCS#11 URIs in their configuration/commandline in place of filenames, and just work. (cf. #170, but that also covers using the system-configured tokens automatically, which is this one).

The available libraries shouldn't just make it *easy* for application authors, but should almost make it hard for them to get it *wrong*. Which is why I'm not keen on application authors having to piece together bits from multiple places to do something that works.

Background: I wrote the [OpenConnect](https://www.infradead.org/openconnect/pkcs11.html)  VPN client, have developed strong views over the years on how we should make life simple for users and how the crypto libraries actually make it fairly hard for application authors to do so. Was recently pointed at https://github.com/aws/rolesanywhere-credential-helper/pull/27 which mostly just made me throw my toys out of the pram and [reimplement it](https://github.com/aws/rolesanywhere-credential-helper/pull/34) to Just Work with e.g. `--certificate pkcs11:manufacturer=piv_II;id=%01` as it should. And now I'm trying to resolve the issue of how they got to that point in the first place, because the available libraries didn't help them get it right.

**Comment by miekg** [comment]
> That makes sense, although it means that applications probably shouldn't be using this directly; they should only really use it through a wrapper such as the go-pkcs11uri library?

yes, and that layering is also a clean separation of responsibilities
