### ISSUE TITLE
Error running the PKCS11 package on Windows

### ISSUE THREAD

**Issue by Victor7k** [miekg/pkcs11#173]
I'm trying to create a code in Golang using this package, but even after installing it and checking all the environment variables I'm getting the same error every time. Someone knows how can I fix this?
Example: undefined: pkcs11.New compiler(UndeclaredImportedName)

My Go Version is go1.21.1 windows/amd64

![Problema com PKCS11](https://github.com/miekg/pkcs11/assets/62629201/f0bb88e4-6451-4b8e-bac1-e2b77b4d884a)

**Comment by reznik99** [comment]
I am having the same issue on **Windows** with:
- Go v1.21.3
- Go v1.20.10

**Comment by onrkrsy** [comment]
@Victor7k  did you solve the problem?
@miekg do you have any idea what is the real solution for that problem? is that about windows and VS Code or about version of Go?

**Comment by Victor7k** [comment]
@onrkrsy Yes I solved. I just needed to enable the CGO to 1 in the Terminal with the command "go env -w CGO_ENABLED=1" or "$env:CGO_ENABLED = 1".
