### ISSUE TITLE
tag a release

### ISSUE THREAD

**Issue by jfrazelle** [miekg/pkcs11#19]
Hi,

Sorry to bother... but can you maybe tag a release, then when we vendor into docker its prettier not based off a sha :)

thanks!

**Comment by jfrazelle** [comment]
it can just be from master :)

**Comment by miekg** [comment]
See longer discussion here: https://github.com/miekg/dns/issues/280, which sort of applies here...
I can tag, but I am sure I will forget, as nothing is automated for released this...

**Comment by jfrazelle** [comment]
No worries

**Comment by onlyjob** [comment]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Versioning provides safety margin for situations like "ops, we've made a mistake but reverted problematic commit in master". Presumably tagged version/release is better tested/reviewed than random snapshot of "master" branch.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning
