### ISSUE TITLE
Unable to save keys

### ISSUE THREAD

**Issue by ezbercih** [miekg/pkcs11#22]
I am able to create pair of RSA keys, encrypt and decrypt using them however these keys are not persistent for some reason. Every invocation of my sample code generates a new set. I went through the sqlite db to find the keys but all the tables except for Token are empty. Does the session need to be initialized in a certain way for the keys to be stored? I am using softhsm for this test. Any ideas what might be going wrong?

**Comment by miekg** [comment]
you'll have to debug some, usually I instrument the softhsm lib and see what happens inside to check things like this

**Comment by djadala** [comment]
do you set `pkcs11.NewAttribute(pkcs11.CKA_TOKEN, true)` in keyTemplate ?
