### ISSUE TITLE
(Cross) compile instructions for win32

### ISSUE THREAD

**Issue by wernerb** [miekg/pkcs11#24]
I use your library in another project and I am very interested on how to (cross) compile correctly for win32

**Comment by wernerb** [comment]
Adding cgo directives such as in #28 allows cross compilation with `xgo`

Execute with:
```
xgo --deps="http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz" "--targets=darwin/*,linux/amd64,linux/arm-7,win1dows/386" .
```

windows/amd64 errors

**Comment by miekg** [comment]
Is this still a problem? I don't have or use Windows so I can easily help out.

**Comment by wernerb** [comment]
Hey! Yes this is still a problem. oddly enough win32 does work, but amd64 does not as you can see with the above errror :)

**Comment by alukyan** [comment]
I am trying to use this package to make my Golang code to talk to Yubikey on Windows: scenarios include singing digests with private key on Yubikey for TLS and SSH protocols.

I got cross compilation for Windows amd64 work, but I get runtime failure in pkcs11.Ctx.Initialize().

>tls-client-windows-4.0-amd64.exe c:\Windows\System32\opensc-pkcs11.dll
Enter Yubikey PIN:6 digits of PIN entered
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7560c5
PC=0x7560c5
signal arrived during external code execution

github.com/miekg/pkcs11._Cfunc_Initialize(0x1387c20, 0xc04206aa80, 0x0)
        github.com/miekg/pkcs11/_obj/_cgo_gotypes.go:1156 +0x54
github.com/miekg/pkcs11.(*Ctx).Initialize.func1(0x1387c20, 0xc04206aa80, 0x1387c20)
        /ext-go/1/src/github.com/miekg/pkcs11/pkcs11.go:782 +0xaa
github.com/miekg/pkcs11.(*Ctx).Initialize(0xc04206c028, 0x25, 0xc04206c028)
        /ext-go/1/src/github.com/miekg/pkcs11/pkcs11.go:782 +0xda
main.NewYubikeySigner(0xc042089d18, 0x6, 0xc042089e90, 0x1, 0x1)
        /ext-go/1/src/griffin/tls-client/main.go:245 +0x6b
main.main()
        /ext-go/1/src/griffin/tls-client/main.go:62 +0x23b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
rax     0x7ffa8e329f380000
rbx     0xc042089970
rcx     0xc04206aa80
rdi     0xc042089970
rsi     0x7940c0
rbp     0x9ffd10
rsp     0x9ffcf0
r8      0xc0420101a0
r9      0x0
r10     0xc04206aa80
r11     0x6813db
r12     0x0
r13     0x6
r14     0x0
r15     0xf2
rip     0x7560c5
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

If someone managed to get this package to work on Windows can you please share what PKCS11 module you used?

**Comment by mtharp** [comment]
Sounds like you might be hitting the problem I found in #48 -- see if that patch fixes it for you.

**Comment by alukyan** [comment]
Thank you very much! Your patch helped!!

**Comment by miekg** [comment]
Think we should (finally) merge that. Let me do that now.
