### ISSUE TITLE
NewMechanism(pkcs11.CKM_AES_CBC, nil)} requires extra attributes

### ISSUE THREAD

**Issue by keithballdotnet** [miekg/pkcs11#3]
I am able to create a AES key but I cant encrypt...

err = p.EncryptInit(session,
[]*pkcs11.Mechanism{pkcs11.NewMechanism(pkcs11.CKM_AES_CBC, nil)}, aesKey)
if err != nil {
panic(fmt.Sprintf("EncryptInit() failed %s\n", err))
}

It appears that the mechanism requires extra attributes,

See the AES example here:
http://www-01.ibm.com/support/knowledgecenter/linuxonibm/com.ibm.linux.z.lxce/lxce_linklib_crypto_samples.html

You make a comment in the code when creating the mechanism.

// TODO(miek): Not seen anything as elaborate as Attributes, so for know do
nothing.

**Comment by Inflatablewoman** [comment]
If I get change I can create a PR with the update to softhsm2.  Let me know if you think that's a good idea?

**Comment by Legrandin** [comment]
CBC always requires an IV, so it is pretty understandable your code fails (you pass `nil` instead of 16 bytes).
