### ISSUE TITLE
GetMechanismList fails with CKR_BUFFER_TOO_SMALL on first call

### ISSUE THREAD

**Issue by FStelzer** [miekg/pkcs11#30]
When calling GetMechanismList on a Gemalto .NET Token the C function will return CKR_BUFFER_TOO_SMALL on the first call (with the Mechanism List being a NULL Pointer).
This is apparently in violation of the specs which states that the function should return CKR_OK. 

However i don't see much harm done to extend the error check in pkcs11.go:118 to be:
if (e != CKR_OK && e != CKR_BUFFER_TOO_SMALL) {
    return e;
}

With this addition i was able to successfully query the supported mechanisms from the Gemalto card.

Maybe someone can cross-check how this is handled in other pkcs11 implementations? The Token works fine in other applications.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/pkcs11] GetMechanismList fai..." ]
>When calling GetMechanismList on a Gemalto .NET Token the C function will return CKR_BUFFER_TOO_SMALL on the first call (with the Mechanism List being a NULL Pointer).
>This is apparently in violation of the specs which states that the function should return CKR_OK.

Where is this exactly stated?

>However i don't see much harm done to extend the error check in pkcs11.go:118 to be:
>if (e != CKR_OK && e != CKR_BUFFER_TOO_SMALL) {
>    return e;
>}

Isn't it better to also check if mechanism list is null?

>With this addition i was able to successfully query the supported mechanisms from the Gemalto card.
>
>Maybe someone can cross-check how this is handled in other pkcs11 implementations? The Token works fine in other applications.

/Miek

--
Miek Gieben

**Comment by FStelzer** [comment]
http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959741
Section 5.5 Function C_GetMechanismList states:
"1.     If pMechanismList is NULL_PTR, then all that C_GetMechanismList does is return (in *pulCount) the number of mechanisms, without actually returning a list of mechanisms.  The contents of *pulCount on entry to C_GetMechanismList has no meaning in this case, and the call returns the value CKR_OK."

It might indeed be better to just check if the mechlen pointer is a valid ULONG as it's dereferenced in the next line.

**Comment by miekg** [comment]
I don't want  to randomly add "fixes" for implementations that do the wrong thing. However adding a #define or something else also doesn't work because cgo does not allow you to enable/disable this at compile time.

OTOH this library call the function with NULL - so your first proposed solution might not be that strange

**Comment by miekg** [comment]
Can you send a PR that add the `CKR_BUFFER_TOO_SMALL` check there as well? If future cases pop up we can rethink this approach.
