### ISSUE TITLE
VerifyRecover call C.DecryptVerifyUpdate ? Is this correct ?

### ISSUE THREAD

**Issue by clashion** [miekg/pkcs11#36]
I notice in pkcs11.go, around line 1399, the VerifyRecover is invoking C.C.DecryptVerifyUpdate .
Is this correct ?

// VerifyRecover verifies a signature in a single-part
// operation, where the data is recovered from the signature.
func (c *Ctx) VerifyRecover(sh SessionHandle, signature []byte) ([]byte, error) {
    var (
        data    C.CK_BYTE_PTR
        datalen C.CK_ULONG
    )
    e := C.DecryptVerifyUpdate(c.ctx, C.CK_SESSION_HANDLE(sh), C.CK_BYTE_PTR(unsafe.Pointer(&signature[0])), C.CK_ULONG(len(signature)), &data, &datalen)
    if toError(e) != nil {
        return nil, toError(e)
    }
    h := C.GoBytes(unsafe.Pointer(data), C.int(datalen))
    C.free(unsafe.Pointer(data))
    return h, nil
}

**Comment by miekg** [comment]
No, that's probably wrong.
