### ISSUE TITLE
Panic in allocate if an empty byte slice is passed

### ISSUE THREAD

**Issue by tadukurow** [miekg/pkcs11#37]
Allocate at types.go:39 panics if and empty slice is passed, because it takes the pointer of obj[0]

```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x46eb180, 0xc820014060)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
path/vendor/github.com/miekg/pkcs11.(*arena).Allocate(0xc820122f70, 0x4bbabf8, 0x0, 0x0, 0x2, 0x2)
    path/vendor/github.com/miekg/pkcs11/types.go:39 +0x244  path/vendor/github.com/miekg/pkcs11.cAttributeList(0xc82013c950, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
    path/vendor/github.com/miekg/pkcs11/types.go:210 +0x1b1
path/vendor/github.com/miekg/pkcs11.(*Ctx).FindObjectsInit(0xc820030280, 0x1, 0xc82013c950, 0x2, 0x2, 0x0, 0x0)
    path/vendor/github.com/miekg/pkcs11/pkcs11.go:1078 +0x5c
```

Ran into this because softhsm doesn't add a CKA_ID by default, which if searched in turn returns an empty slice.

**Comment by miekg** [comment]
Can we make the case of saying this is a documentation problem?

**Comment by tadukurow** [comment]
We could, but looking at NewAttribute it would get the same behaviour with an empty string and since Allocate is exported it would be nice if we could solve this. I understand it's problematic since Allocate doesn't return an error type.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/pkcs11] Panic in allocat..." ]
>We could, but looking at NewAttribute it would get the same behaviour with an empty string and since Allocate is exported it would be nice if we could solve this. I understand it's problematic since Allocate doesn't return an error type.

Indeed. Is this worth breaking backwards compat for... And if we do we should
add error returns to more (or at least look for methods that don't atm).

/Miek

--
Miek Gieben
