### ISSUE TITLE
Add negative build flag to pkcs11.go to make build optional

### ISSUE THREAD

**Issue by smithbk** [miekg/pkcs11#46]
Since this package introduces a dependency on libtool, other packages which include this will fail to compile with the missing "ltdl.h" file error when not installed.  It would be nice to:
1) include a list or a link to a list of what to install on various platforms to meet this prereq, and
2) include a negative build flag on the 1st line of pkcs11.go similar to the following:
        // +build !nopkcs11
This will allow products which import github.com/miekg/pkcs11 to be built as follows if they don't want to or can't install libtool for some reason on a platform, without requiring that products modify their vendor folder:
     go get -tags nopkcs11 github.com/foo/bar

**Comment by miekg** [comment]
That build tag is a good idea. Please send a PR for it.

Re 1: I don't have any cycles to keep such a list up to date
