### ISSUE TITLE
Latest macOS Sierra update causes program termination at startup

### ISSUE THREAD

**Issue by bepayne** [miekg/pkcs11#49]
After updating to macOS Sierra 10.12.4 (Xcode 8.3) programs that include the pkcs11 package get killed at startup.  This includes programs (e.g., unit tests) that include the package in a dependency chain and do not use the pkcs11 functions directly.

Running one such program under gdb produced the following output:

>Reading symbols from ./certs.bad...
>warning: `/tmp/go-build198504308/crypto/x509/_obj/root_cgo_darwin.cgo2.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/net/_obj/_cgo_export.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/net/_obj/cgo_resnew.cgo2.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/net/_obj/cgo_unix.cgo2.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/runtime/cgo/_obj/gcc_amd64.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/runtime/cgo/_obj/gcc_context.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/runtime/cgo/_obj/gcc_darwin_amd64.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/runtime/cgo/_obj/gcc_libinit.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/runtime/cgo/_obj/gcc_setenv.o': can't open to read symbols: No such file or directory.
>
>warning: `/tmp/go-build198504308/runtime/cgo/_obj/gcc_util.o': can't open to read symbols: No such file or directory.
>
>warning: `/var/folders/f0/1chs6k912_l0p5fzvx_n6zmm0000gn/T/go-build889960085/bb.commandscape.com/cs/global/vendor/github.com/miekg/pkcs11/_obj/_cgo_export.o': can't open to read symbols: No such file or directory.
>
>warning: `/var/folders/f0/1chs6k912_l0p5fzvx_n6zmm0000gn/T/go-build889960085/bb.commandscape.com/cs/global/vendor/github.com/miekg/pkcs11/_obj/pkcs11.cgo2.o': can't open to read symbols: No such file or directory.
>
>warning: `/var/folders/f0/1chs6k912_l0p5fzvx_n6zmm0000gn/T/go-build889960085/bb.commandscape.com/cs/global/vendor/github.com/miekg/pkcs11/_obj/types.cgo2.o': can't open to read symbols: No such file or directory.
>
>warning: `/var/folders/f0/1chs6k912_l0p5fzvx_n6zmm0000gn/T/go-link-749695904/go.o': can't open to read symbols: No such file or directory.
done.
>(gdb) run
>Starting program: /Users/bepayne/src/bb.commandscape.com/cs/global/certs.bad
>During startup program terminated with signal SIGKILL, Killed.

After removing the pkcs11 dependency, the same unit test under gdb produced:

>Reading symbols from ./certs.good...done.
>Loading Go Runtime support.
>(gdb) run
>Starting program: /Users/bepayne/src/bb.commandscape.com/cs/global/certs.good
>[New Thread 0x1403 of process 7406]
>warning: unhandled dyld version (15)
>--- FAIL: TestPool (0.00s)
>       	certs_test.go:37: Pool error: open testdata/self_signed.pem: no such file or directory
>FAIL
>[Inferior 1 (process 7406) exited with code 01]

**Comment by miekg** [comment]
I don't use Xcode so I can't help here (nor do I run MacOS)

**Comment by nmelo** [comment]
A workaround for this issue seems to be building your binaries with:

`go build -ldflags -s`

This issue is being discussed in the go repo: 
https://github.com/golang/go/issues/19734
