### ISSUE TITLE
Sign example doesn't work with softhsm2

### ISSUE THREAD

**Issue by diogomonica** [miekg/pkcs11#5]
I got everything setup, but I can't get your Signing example (slightly modified with error printing), to work:

```bash
✗ go run hsmtest.go
pkcs11: 0xD1: CKR_TEMPLATE_INCONSISTENT
```
Code here: https://gist.github.com/diogomonica/89dd1e913c66421df284

This is running on a OS X 10.10.3. I can run the SHA1 example from the Readme (the softhsm seems to be working correctly)

**Comment by diogomonica** [comment]
I got it to work by removing 

```
pkcs11.NewAttribute(pkcs11.CKA_KEY_TYPE, pkcs11.CKO_PUBLIC_KEY),
```
and
```
pkcs11.NewAttribute(pkcs11.CKA_KEY_TYPE, pkcs11.CKO_PRIVATE_KEY),
```
From the PublicKey and PrivateKey templates (respectively).

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [pkcs11] Sign example doesn't w..." ]
>I got it to work by removing
>
>```
>pkcs11.NewAttribute(pkcs11.CKA_KEY_TYPE, pkcs11.CKO_PUBLIC_KEY),
>```
>and
>```
>pkcs11.NewAttribute(pkcs11.CKA_KEY_TYPE, pkcs11.CKO_PRIVATE_KEY),
>```
>From the PublicKey and PrivateKey templates (respectively).

Any idea why this should be done for hsm2?


/Miek

--
Miek Gieben

**Comment by diogomonica** [comment]
No. Unfortunately this was found mostly through trial and error.

**Comment by diogomonica** [comment]
For what it's worth there is one failing tests with SoftHSM2:

```
--- FAIL: TestGetAttributeValue (0.01s)
	pkcs11_test.go:103: err pkcs11: 0x82: CKR_OBJECT_HANDLE_INVALID
```
