### ISSUE TITLE
Is there support for concatenation for key derivation?

### ISSUE THREAD

**Issue by dreemkiller** [miekg/pkcs11#50]
Is there support for the key derivation method CKM_CONCATENATE_BASE_AND_DATA? It requires the structure CK_KEY_DERIVATION_STRING_DATA be sent in as the Parameter to the Mechanism, which I don't see in the code. If I just pass the data in, arena.Allocate is just going to calloc the size of the byte array, but the pkcs11 API is expecting the byte array and a CK_ULONG.

When I run it naively, just passing the byte array as the Parameter in the mechanism, I get CKR_MECHANISM_INVALID.

If there's no support, I can either jury rig it in my code (not ideal) or implement it in your package and then do a pull request.

If there is support, great! How does it work?

Thanks for implementing this very useful package.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/pkcs11] Is there support for..." ]
>Is there support for the key derivation method CKM_CONCATENATE_BASE_AND_DATA? It requires the structure CK_KEY_DERIVATION_STRING_DATA be sent in as the Parameter to the Mechanism, which I don't see in the code. If I just pass the data in, arena.Allocate is just going to calloc the size of the byte array, but the pkcs11 API is expecting the byte array and a CK_ULONG.
>
>When I run it naively, just passing the byte array as the Parameter in the mechanism, I get CKR_MECHANISM_INVALID.
>
>If there's no support, I can either jury rig it in my code (not ideal) or implement it in your package and then do a pull request.

Think it is best to do a PR and see how generic and useful it looks? We may need
to extend Paramater or make it a interface.

>If there is support, great! How does it work?
>
>Thanks for implementing this very useful package.

Thanks!

**Comment by dreemkiller** [comment]
Update on this: I have successfully constructed the CK_KEY_DERIVATION_STRING_DATA struct, and passed it into the underlying PKCS11 implementation (SoftHSM).
However, as it turns out, SoftHSM does not support this key derivation method, nor does Opencryptoki (the other open source implementation that I am aware of). Thus, without buying an HSM board or perhaps a proprietary software implementation (if they exist), there's no real way to test it.

I'll leave it up to you, but I think this should probably be closed. If you disagree, I can create a pull request for my code and you can take a look at it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/pkcs11] Is there support..." ]
>Update on this: I have successfully constructed the CK_KEY_DERIVATION_STRING_DATA struct, and passed it into the underlying PKCS11 implementation (SoftHSM).
>However, as it turns out, SoftHSM does not support this key derivation method, nor does Opencryptoki (the other open source implementation that I am aware of). Thus, without buying an HSM board or perhaps a proprietary software implementation (if they exist), there's no real way to test it.
>
>I'll leave it up to you, but I think this should probably be closed. If you disagree, I can create a pull request for my code and you can take a look at it.

I probably don't have enough time to take a deep look. And no SoftHSM support
means there will be little testing. All suboptimal, so I'm in favor of closing.

**Comment by dreemkiller** [comment]
Closing. Thanks for the support
