### ISSUE TITLE
Panic when PKCS11 library is not accessible

### ISSUE THREAD

**Issue by jefferai** [miekg/pkcs11#54]
We're seeing a panic from 

https://github.com/miekg/pkcs11/blob/eda1d775a087f2a96fec7c7876ea94dea43e6027/pkcs11.go#L782

when the library is inaccessible, e.g. if the user has no permissions on it. Unfortunately this is all the data I have, just that it's coming from this line and it's a SIGSEGV.

**Comment by miekg** [comment]
Closing. Not saying this is WAI, but making it crash if it can't use a library seems to be a good way of saying that things will not work.

**Comment by jefferai** [comment]
A returned error would be preferable. We're bubbling up the error anyways on our end, but the fact that the function might also panic was unexpected. It isn't documented as such, and normal expectations in Go are that applications panic, libs error.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/pkcs11] Panic when PKCS1..." ]
>A returned error would be preferable. We're bubbling up the error anyways on our end, but the fact that the function might also panic was unexpected. It isn't documented as such, and normal expectations in Go are that applications panic, libs error.

I won't have time to work on this, but feel free to send a PR that fixes this.
