### ISSUE TITLE
Provide crypto.Signer interface

### ISSUE THREAD

**Issue by fzakaria** [miekg/pkcs11#57]
It would be really useful if an example or just an implementation of the crypto.Signer interface was provided https://golang.org/pkg/crypto/#Signer

Plenty of other packages use it like _ssh_ which would mean I can use PKCS#11 for my SSH code.
I couldn't figure it out myself at the moment.

**Comment by miekg** [comment]
Nice plan! Maybe we should do it in https://github.com/miekg/pkcs11/pull/56? (or after that is merged)

**Comment by fzakaria** [comment]
Here is a use case I am envisioning (create an ssh ClientConfig)

```
	u, err := user.Current()
	if err != nil {
		return nil, err
	}

	pin := "my fake pin"
        module, _ := p11ez.OpenModule("/path/to/module.so")
        slots, _ := module.Slots()
        session, _ := slots[0].OpenSession()
        session.Login(user, pin)


        pk, _ := session.FindObject(CKO_PRIVATE_KEY)
        
       privateKeySigner := p11ez.PrivateKey(pk)
        signer, err := ssh.NewSignerFromSigner(privateKeySigner)
	
        return &ssh.ClientConfig{
		User: u.Username,
		Auth: []ssh.AuthMethod{
			ssh.PublicKeys(signer),
		},
	}, nil
```

**Comment by nfewx** [comment]
Hi, https://github.com/thalesignite/crypto11 implements crypto.Signer in terms of miekg/pkcs11.

**Comment by miekg** [comment]
Just should be mentioned in the README I think. Care for a PR?

**Comment by nfewx** [comment]
https://github.com/miekg/pkcs11/pull/58
