### ISSUE TITLE
Cross compiling for Win10 (Yubikey)

### ISSUE THREAD

**Issue by netmiller** [miekg/pkcs11#61]
Golang newbie question: I can't figure out how to build (cross-compile) my __signing-test-prog__ for Windows usage. I'm working in OsX and managed to get all done without any (bigger) problem .

This is ok :

````
iMac@pkcs11$ GOOS=darwin GOARCH=amd64 go build -o t5.osx test5.go
iMac@pkcs11$ ./t5.osx
   ..... etc ... works like charm .....
````

Cross-compiling Win .exe :

````
► iMac@pkcs11$ GOOS=windows GOARCH=amd64 go build -o t5.exe test5.go
# command-line-arguments
./test5.go:13:7: undefined: pkcs11.New
./test5.go:42:27: undefined: pkcs11.Attribute
./test5.go:81:25: undefined: pkcs11.Mechanism
````

and here's my code (at least beginning og code) :

````
package main

import (
	"encoding/base64"
	"fmt"

	"github.com/miekg/pkcs11"
)

func main() {

	// p := pkcs11.New("/usr/local/lib/softhsm/libsofthsm2.so")
	p := pkcs11.New("./lib/libykcs11.dylib")      // <-- line 13 !!!
	p.Initialize()

	defer p.Destroy()
	defer p.Finalize()

	slots, err := p.GetSlotList(true)
	if err != nil {
		fmt.Println(err)
	}

.... etc .....

````
 
My HSM is Yubikey 4 (PIV) , and it is configured and works OK.

Any workaround for getting this cross-compile done with OsX. Tried also in Win10, but my toolchain there is lacking at least Libtool etc. Anyway, for me it is simplest to develop with osx and only cross-compile for Win10.

Thanks for advise. Sorry but I'm just learning Golang more serious, but have to solve this quickly.

**Comment by miekg** [comment]
Don't know any windows, but:
~~~
GOOS=windows GOARCH=amd64 go build -o t5.exe test5.go
~~~
Not sure if all deps are cross compile correctly here. What happen with just a `go clean` and `go build` i.e. don't specify any Go files

Also we use cgo so cross compiling might harder?

**Comment by netmiller** [comment]
I tried to get Yubikey:s own dll ( libykcs11-1.dll ) and put it in my `./lib/` dir.
Then changed source code:

````
// p := pkcs11.New("./lib/libykcs11.dylib")
p := pkcs11.New("./lib/libykcs11-1.dll")
````

so building should at least find valid .dll (works on Win).
But it throws same errors: ( __I'm still in Osx env__ )

````
► iMac@pkcs11$ GOOS=windows GOARCH=amd64 go build -o t5.exe test5.go
# command-line-arguments
./test5.go:14:7: undefined: pkcs11.New
````
I have not enough experience compiling and cross-compiling !! So it was just a "brief try".

Do you think it has possibility to work if moving whole building-phase under Windows-env.
I must figure out what I'm missing in my toolchain (Windows), but is it worth to try.

I found also tool called __gonative__ (<https://github.com/inconshreveable/gonative>).
But it seems a bit old, and I'm not sure if it might help??

Also some article <https://inconshreveable.com/04-30-2014/cross-compiling-golang-programs-with-native-libraries/>. 

OK, maybe I will try pure Win-env for building, if you don't find anything to try within osx ?
Or do you think it doesn't help??

**Comment by netmiller** [comment]
What about tool called __gox__  ( <https://github.com/mitchellh/gox> ) ??
Not tried yet, but seems up-to-date tool; is it worth trying?

**Comment by miekg** [comment]
Just the Go tool chain should be enough to cross build even with cgo (provided you have the libraries and headers installed).

**Comment by netmiller** [comment]
Maybe not, you are right. What libs and headers do you mean (just remember I'm quite newbie with Go and C).

**Comment by netmiller** [comment]
Can you figure where I have to locate header files (ykpiv.h).

And should I have win_dll (libykcs11-1.dll) in my building env or is it needed just when running in windows?

Can it be some __cgo__ flag which I'm missing (CGO_CFLAGS or CGO_LDFLAGS).

**Comment by mtharp** [comment]
I've had luck using xgo https://github.com/karalabe/xgo (requires docker)

Example:
xgo --targets windows/amd64 --deps=http://mirror.clarkson.edu/gnu/libtool/libtool-2.4.6.tar.gz --ldflags '-extldflags -static' .

**Comment by kaaposc** [comment]
@netmiller try `xgo`. Here's what worked for me:
1. put your package in `$GOPATH/src` (I tried from other place and xgo failed with `can't load package: package .: no Go files in /`)
2. `cd` into `$GOPATH/src/yourpackage`
3. `xgo --deps="http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz" --targets windows/amd64 .` (I need only win64)

**Comment by crackcomm** [comment]
Seems to work when compiled from msys2 terminal.

**Comment by shrirangrk** [comment]
@netmiller  were you able to get a solution for this?
