### ISSUE TITLE
invalid LDFLAGS break build with go1.9.4 / go1.10rc2

### ISSUE THREAD

**Issue by dmitris** [miekg/pkcs11#63]
On Linux, I'm getting the following error when trying to build the master version with go1.9.4:
```
$ go install ./...
go build github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -Wl,--no-as-needed
```

On Mac OS, getting the error:
```
$ go install ./...
go build github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool
```

Same errors with go1.10rc2.  This is likely be due to changes / security fixes in https://github.com/golang/go/issues/23672

@miekg

**Comment by miekg** [comment]
:-(

Can you send a PR?

**Comment by dmitris** [comment]
https://github.com/miekg/pkcs11/pull/64

I think that `-Wl,--no-as-needed` is missing in Go from https://github.com/golang/go/blob/master/src/cmd/go/internal/work/security.go#L88-L89

Is `--no-as-needed` a must-have?  You can install the package with `CGO_LDFLAGS_ALLOW='-Wl,--no-as-needed' go install` but it's somewhat inconvenient for users to be forced to do it...

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/pkcs11] invalid LDFLAGS ..." ]
>https://github.com/miekg/pkcs11/pull/64
>
>I think that `-Wl,--no-as-needed` is missing in Go from https://github.com/golang/go/blob/master/src/cmd/go/internal/work/security.go#L88-L89
>
>Is `--no-as-needed` a must-have?  You can install the package with `CGO_LDFLAGS_ALLOW='-Wl,--no-as-needed' go install` but it's somewhat inconvenient for users to be forced to do it...

I don't know. This as all working, and now "they" broke it

**Comment by dmitris** [comment]
I suggest to start with merging this as is, for the sake of the `Darwin`ists, and then figure out what to do for Unix (not sure about Windows).

**Comment by tocosonic** [comment]
Simply migrate to GO version 1.10. This erroneous behaviour has been fixed in the most recent version.

**Comment by ilfrich** [comment]
Seems to still be an issue with 1.10 if you use an older library.

There's a workaround in the hyperledger/fabric#67 issue linked above using an environment variable to override the error: `CGO_LDFLAGS_ALLOW="-I.*" <your-build-command>`

**Comment by andlabs** [comment]
Why do you need `-I` in `LDFLAGS`? cgo separates the compiler and linker phases, and `-I` is only relevant in the former. Unless there's something I'm missing?
