### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by cesarkuroiwa** [miekg/pkcs11#69]
Please make it compatible with FreeBSD.

Just add to pkcs11.go:

```
#cgo freebsd CFLAGS: -I/usr/local/include/
#cgo freebsd LDFLAGS: -lltdl -L/usr/local/lib/
```

It worked for me

Thanks

**Comment by miekg** [comment]
cool, just send a PR with that.

**Comment by miekg** [comment]
This has all changed recently, think this is not relevant anymore
