### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by jsha** [miekg/pkcs11#7]
In https://github.com/letsencrypt/boulder/pull/795 and https://github.com/cloudflare/cfssl/issues/322 we're trying to figure out the thread safety properties of the pkcs11 library. Is pkcs11 expected to work from multiple threads / goroutines? Are there any special considerations we need to take?

Thanks,
Jacob

**Comment by miekg** [comment]
I never actually thought about that, but I think the answer is yes: multiple threads/goroutines should be safe. A single `ctx` should be good to be shared between go routines.

Of course this might also depend on the HSM backend that is used...

**Comment by miekg** [comment]
Actually a test demonstrating concurrent go-routines doing stuff is welcome.

**Comment by miekg** [comment]
Why is the session not thread safe?

**Comment by jsha** [comment]
From the PKCS#11 doc, section 6.7.6:

> A consequence of the fact that a single session can, in general, perform only one operation at a time is that an application should never make multiple simultaneous function calls to Cryptoki which use a common session. If multiple threads of an application attempt to use a common session concurrently in this fashion, Cryptoki does not define what happens. This means that if multiple threads of an application all need to use Cryptoki to access a particular token, it might be appropriate for each thread to have its own session with the token, unless the application can ensure by some other means (e.g., by some locking mechanism) that no sessions are ever used by multiple threads simultaneously. This is true regardless of whether or not the Cryptoki library was
initialized in a fashion which permits safe multi-threaded access to it. Even if it is safe to access the library from multiple threads simultaneously, it is still not necessarily safe to use a particular session from multiple threads simultaneously.

**Comment by miekg** [comment]
Thanks.

**Comment by onesick** [comment]
Hi guys, I am not sure if I understood this thread correctly. But I had the same question with multiple thread using the same session. Some other library like C# pkcs11 library looks to be using master login session, and open thread sessions. In which means that log in happens once per app life cycle. But since this library opens session first, and logs in, I do similar as @jsha used the re-initiated the whole process including log in. 
For example, every decrypt request, I initialize by finding slot, opening session, and log in with the session, and close session, like his test code. But would it not affect the performance? Will it depend on how HSM handle log-in session?

**Comment by jsha** [comment]
There's some pretty good reference code in https://github.com/letsencrypt/pkcs11key/blob/master/key.go now. Basically, if the private key has CKA_ALWAYS_AUTHENTICATE, you need to log in again each time. Otherwise you can log in once and hold the session open. You still need to ensure there is no concurrent access to a single session by multiple threads (or goroutines). You can do this with mutexes. For high performance you'll want to open multiple sessions at once and have a pool. You can see examples at https://github.com/letsencrypt/pkcs11key/blob/master/pool.go.

**Comment by jsha** [comment]
I'm afraid I don't have any experience with derived keys.

**Comment by onesick** [comment]
Ok. Thanks!

**Comment by ankitpatelce** [comment]
Thank to All.
This Discussion solved my problem.

How much Session we can onpen in each slot once?
Any idea? Approximatly in major HSMs?
