### ISSUE TITLE
go 1.10.2 shows error:  invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool

### ISSUE THREAD

**Issue by zcm211** [miekg/pkcs11#75]
go build vendor/github.com/miekg/pkcs11: invalid flag in #cgo LDFLAGS: -I/usr/local/share/libtool

**Comment by FerminPan** [comment]
go version go1.10.1 darwin/amd64
go get -u -v github.com/miekg/pkcs11

github.com/miekg/pkcs11 (download)
github.com/miekg/pkcs11
# github.com/miekg/pkcs11
../github.com/miekg/pkcs11/pkcs11.go:28:10: fatal error: 'ltdl.h' file not found
#include <ltdl.h>
         ^~~~~~~~
1 error generated.

**Comment by miekg** [comment]
changed recently.
