### ISSUE TITLE
Does this library work with CloudHSM?

### ISSUE THREAD

**Issue by matthewcummings** [miekg/pkcs11#77]
It appears that it does, based on this comment: https://github.com/miekg/pkcs11/blame/287d9350987cc9334667882061e202e96cdfb4d0/params.go#L29

**Comment by matthewcummings** [comment]
Rephrasing my question. . . are there any gotchas I should be aware of when using this with CloudHSM?

**Comment by matthewmdn** [comment]
+1

**Comment by prologic** [comment]
Also curious to know whether this library works with the [IBM Luna HSM](https://www.ibm.com/support/knowledgecenter/en/SS9H2Y_7.5.0/com.ibm.dp.doc/lunahsm.html)

**Comment by mtharp** [comment]
Yes, I am using Luna SA extensively. As for CloudHSM I was able to test and verify the PR linked in the first comment at the time so I'd call that working.
