### ISSUE TITLE
Does this Library work with a SafeNet HSM?

### ISSUE THREAD

**Issue by Kraust** [miekg/pkcs11#78]
I saw #72 referenced a SafeNet/Gemalto HSM and tried to use this to interface with one and only seemed to be able to interface with a SoftHSM despite thinking that I initializing with the right .so file. Does anyone have any experience with this?

**Comment by vanbroup** [comment]
I'm using this library with multiple HSM and Token vendors including SafeNet, as long you use the right .so file it should be no problem.

Can you share more details about your setup and the error/problem you have?

**Comment by Kraust** [comment]
I apologize, it looks like I was pointing to the wrong .so file.
