### ISSUE TITLE
No way to get number of objects from FindObjects call

### ISSUE THREAD

**Issue by zenazn** [miekg/pkcs11#9]
`FindObjects` takes a maximum number of results to return, and returns a `bool` if there were more results, however there is no way to get the number of results that might have been returned had `max` been larger without randomly trying increasing values for `max`.

The easiest fix here would be to return the number of results instead of the "has more" flag, but that would obviously be a breaking API change for existing users.

**Comment by miekg** [comment]
But an api change would be breaking the pkcs11 compatibility. I don't know
what the canonical pkcs11 way of doing this is though.
